name: vertical_farm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_charts: 25.1.35
  flutter_svg: ^2.0.10+1
  flutter_gemini: ^2.0.3
  dash_chat_2: ^0.0.20
  http: ^1.0.0
  image_picker: ^1.0.7
  flutter_inappwebview: ^5.3.2

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  -  assets/icons/Fat.svg
  -  assets/icons/power.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500